name: emb3rs-gis-module
channels:
  - conda-forge
dependencies:
  - python=
  - osmnx=
  - scikit-learn=
  - numpy=
  - pyomo=5.7
  - haversine=
  - pandas=
  - folium=
  - geopandas=
  - shapely=
  - networkx=
  - colorama=
  - jsonpickle=
  - pip:
      - gurobipy==9.5.1
